# Generated by Django 3.0.3 on 2020-07-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=254)),
                ('Mensaje', models.CharField(max_length=255)),
                ('Fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Tallas', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('XXL', 'XX-Large'), ('XXL', 'XXX-Large'), ('N/A', 'No Aplica'), ('U', 'Única')], max_length=15)),
                ('Tipo', models.CharField(choices=[('respiratoria', 'Protección Respiratoria'), ('guantes', 'Guantes'), ('calzado', 'Calzado'), ('auditivo', 'Protección Auditiva'), ('cara', 'Protección Ojos, Cara y Cabeza'), ('vestuario', 'Vestuarios'), ('señalizacion', 'Señalización'), ('caidas', 'Ergonomía y Protección de Caídas'), ('paños', 'Absorbentes y Paños'), ('auxilios', 'Primeros Auxilios'), ('tapes', 'Cintas y Tapes')], max_length=15)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(upload_to='products_assets/img')),
                ('Hoja_Tecnica', models.FileField(upload_to='products_assets/Hojas_Tecnicas')),
            ],
        ),
    ]
