# Generated by Django 3.0.3 on 2020-07-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Hoja_Tecnica',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tallas',
            field=models.CharField(choices=[('Todas', 'Todas'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('XXL', 'XX-Large'), ('XXL', 'XXX-Large'), ('N/A', 'No Aplica'), ('U', 'Única')], max_length=15),
        ),
    ]
