# Generated by Django 3.0.3 on 2020-07-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200710_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Hoja_Tecnica',
            field=models.FileField(upload_to='Hojas_Tecnicas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Imagen',
            field=models.ImageField(upload_to='img'),
        ),
    ]
