# Generated by Django 3.0.3 on 2020-07-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200713_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Imagen',
            field=models.ImageField(upload_to='Imagen'),
        ),
    ]
