# Generated by Django 3.0.3 on 2020-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200713_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Hoja_Tecnica',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
