# Generated by Django 3.0.3 on 2020-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200714_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Hoja_Tecnica',
            field=models.FileField(upload_to='Hoja_Tecnica'),
        ),
    ]
