# Generated by Django 3.0.3 on 2020-07-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200716_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='Empresa',
            field=models.CharField(default='whatever', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactos',
            name='Mensaje',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tipo',
            field=models.CharField(choices=[('Respirador', 'Protección Respiratoria'), ('Guantes', 'Guantes'), ('Calzado', 'Calzado'), ('Auditivo', 'Protección Auditiva'), ('Visor/Ojos, Cara y Cabeza', 'Protección Ojos, Cara y Cabeza'), ('Vestuario', 'Vestuarios'), ('Señalizacion', 'Señalización'), ('Caidas/Ergonomía', 'Ergonomía y Protección de Caídas'), ('Paños', 'Absorbentes y Paños'), ('Primeros Auxilios', 'Primeros Auxilios'), ('Adhesivos, Cintas y Tapes', 'Cintas y Tapes')], max_length=30),
        ),
    ]
