# Generated by Django 3.0.3 on 2020-08-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200806_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Unidades',
            field=models.CharField(choices=[('Par', 'PAR'), ('Paquete', 'PQT'), ('Paquete de 8', 'PQT8'), ('Pieza', 'PZA'), ('Cajita de 100', 'CJTA100'), ('Cajita de 50', 'CJTA50'), ('Conjunto', 'CONJ'), ('Rollo', 'ROLL'), ('Tubo', 'TB')], max_length=15),
        ),
    ]
