# Generated by Django 3.0.3 on 2020-08-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200806_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Tipo',
            field=models.CharField(choices=[('Protección Respiratoria', 'P. Resp'), ('Guantes', 'Gnts'), ('Calzado', 'Clzdo'), ('Protección Auditiva', 'P. Aud'), ('Protección Ojos, Cara y Cabeza', 'P. OCC'), ('Vestuario', 'Vest'), ('Señalización', 'Señalizacion'), ('Ergonomía y Protección de Caídas', 'Ergonomía y P. C'), ('Absorbentes y Paños', 'Absorb y Paños'), ('Primeros Auxilios', 'P. Aux'), ('Adhesivos, Cintas y Tapes', 'Adhesivos')], max_length=50),
        ),
    ]
