# Generated by Django 3.0.3 on 2020-08-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200806_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Tipo',
            field=models.CharField(choices=[('Protección Respiratoria', 'respiratoria'), ('Guantes', 'guantes'), ('Calzado', 'calzado'), ('Protección Auditiva', 'auditiva'), ('Protección Ojos, Cara y Cabeza', 'cabeza'), ('Vestuario', 'vest'), ('Señalización', 'señal'), ('Ergonomía y Protección de Caídas', 'ergon'), ('Absorbentes y Paños', 'absorb'), ('Primeros Auxilios', 'auxiliar'), ('Adhesivos, Cintas y Tapes', 'adhesivos')], max_length=50),
        ),
    ]
