# Generated by Django 3.0.3 on 2020-08-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200806_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Tipo',
            field=models.CharField(choices=[('respiratoria', 'Protección Respiratoria'), ('guantes', 'Guantes'), ('calzado', 'Calzado'), ('auditiva', 'Protección Auditiva'), ('cabeza', 'Protección Ojos, Cara y Cabeza'), ('vest', 'Vestuario'), ('señal', 'Señalización'), ('ergon', 'Ergonomía y Protección de Caídas'), ('absorb', 'Absorbentes y Paños'), ('auxiliar', 'Primeros Auxilios'), ('adhesivos', 'Adhesivos, Cintas y Tapes')], max_length=50),
        ),
    ]
