# Generated by Django 3.0.3 on 2020-08-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200806_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Tipo',
            field=models.CharField(choices=[('Protección Respiratoria', 'Protección Respiratoria'), ('Guantes', 'Guantes'), ('Calzado', 'Calzado'), ('Protección Auditiva', 'Protección Auditiva'), ('Protección Ojos, Cara y Cabeza', 'Protección Ojos, Cara y Cabeza'), ('Vestuario', 'Vestuario'), ('Señalización', 'Señalización'), ('Ergonomía y Protección de Caídas', 'Ergonomía y Protección de Caídas'), ('Absorbentes y Paños', 'Absorbentes y Paños'), ('Primeros Auxilios', 'Primeros Auxilios'), ('Adhesivos, Cintas y Tapes', 'Adhesivos, Cintas y Tapes')], max_length=50),
        ),
    ]
