# Generated by Django 3.0.3 on 2020-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200806_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Tallas',
            field=models.CharField(choices=[('Todas', 'Todas'), ('No Aplica', 'N/A'), ('Única', 'Unica')], max_length=15),
        ),
    ]
